name: edgex-device-gpio
base: core20 
license: Apache-2.0
adopt-info: metadata
  
grade: stable
confinement: strict

epoch: 0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-gpio]
      
plugs:
  device-gpio-config:
    interface: content
    target: $SNAP_DATA/config/device-gpio

  # deprecated
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-gpio

apps:
  device-gpio:
    command: bin/device-gpio $CONFIG_PRO_ARG $CONF_ARG $REGISTRY_ARG
    command-chain:
      - bin/source-env-file.sh
    environment:
      CONFIG_PRO_ARG: "--cp=consul.http://localhost:8500"
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-gpio/res"
      REGISTRY_ARG: "--registry"
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-gpio/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-gpio/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-gpio/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
      - gpio # not connected automatically

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps: [ go/1.18/stable ]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go
    
  device-gpio:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, pkg-config]
    stage-packages: [libzmq5]
    build-snaps: [go/1.18/stable]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build
      
      install -DT cmd/device-gpio $SNAPCRAFT_PART_INSTALL/bin/device-gpio

      RES=$SNAPCRAFT_PART_INSTALL/config/device-gpio/res/
      mkdir -p $RES
      cp    cmd/res/configuration.toml $RES
      cp -r cmd/res/devices $RES
      cp -r cmd/res/profiles $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-gpio
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE
      
  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-gpio.metainfo.xml]
